name: Gradle->Docker->ECS

on:
  push:
    branches:
      - main


jobs:
    build:
        runs-on: ubuntu-20.04
        permissions:
            contents: read

        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

            - name: Build with Gradle Wrapper
              run: ./gradlew build

    dockerize:
        runs-on: ubuntu-20.04
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        
    # push-to-ECR:
    #     runs-on: ubuntu-20.04
    #     permissions:
    #         contents: write

    #     steps:
    #         - uses: actions/checkout@v4
    #         - name: Login to Amazon ECR
    #           id: login-ecr
    #           uses: aws-actions/amazon-ecr-login@v2
    #           with:
    #               registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
    #               access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #               secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    #         - name: Build, tag, and push image to Amazon ECR
    #           run: |
    #               docker build . --file Dockerfile --tag ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-image-name:$(date +%s)
    #               docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-image-name:$(date +%s)
    
    # deploy-to-ECS:
    #     runs-on: ubuntu-20.04
    #     permissions:
    #         contents: write

    #     steps:
    #         - uses: actions/checkout@v4
    #         - name: Login to Amazon ECR
    #           id: login-ecr
    #           uses: aws-actions/amazon-ecr-login@v2
    #           with:
    #               registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
    #               access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #               secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    #         - name: Deploy to Amazon ECS
    #           run: |
    #               aws ecs update-service --cluster my-cluster-name --service my-service-name --force-new-deployment
            